.github/workflows/issue-branch.yml
close #4 
ex) 로그인할 때, 카카오톡 로그인 기능을 추가했습니다.
베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.
ex) 결과물에 대한 스크린 샷
=> feat: 이슈 생성 템플릿 테스트 및 수정

.github/workflows/issue-branch.yml
close #'이슈번호'
ex) 로그인할 때, 카카오톡 로그인 기능을 추가했습니다.
베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.
ex) 결과물에 대한 스크린 샷
=> feat: 이슈 생성 템플릿 수정

tailwind.config.ts
- tablet 744 추가
- 승인만 해주시면 바로 merge할게요.
=> 반응형 태블릿 사이즈 추가

tailwind.config.ts
#9
- text컬러관련 danger삭제, default, inverse값 변경
- 확인해주시고 승인해주시면 merge하겠습니다~
=> text 컬러관련 수정완료

package-lock.json, package.json, src/app/lib/instance.ts
close #35 
- axios 추가
- axios instance 세팅
=> #35 axios setting

src/app/components/common/modal/Modal.tsx
=> style: tailwind css intelliSense 적용

src/app/components/common/input/Input.tsx
close #11 
- `AuthInput` 사용해서 작업하신 부분 import 경로, 이름 수정 부탁드립니다😀
=> rename: 공통 input 이름, 경로 수정

src/app/lib/instance.ts
close #30 
Token 관련 부분이 lint에러 떠서 일단 주석처리하고 올립니다!
=> #30 accessToken 관련 코드 주석처리

src/app/lib/group/postGroup.ts, src/app/lib/image/postImage.ts
close #28 
- team api response 타입 명시
=> 배포 에러 수정 : response 타입 명시

src/app/addteam/page.tsx, src/app/lib/group/postGroup.ts, src/app/lib/image/postImage.ts
=> fix: response 구조 변경

src/app/lib/task/getTask.ts, src/app/lib/tasklist/getTaskList.ts, src/app/lib/tasklist/patchTaskList.ts, src/app/lib/tasklist/postTaskList.ts
=> fix: 타입 명시화

src/app/(component)/datepicker/page.tsx
close #37 
- UI 테스트 페이지이고, `/tasklist` 에서 확인 가능한 컴포넌트라 파일 자체를 지웠습니다!
=> fix: datePicker 빌드 오류 수정

src/app/(routes)/[teamid]/edit/page.tsx
=> fix: response 수정

package-lock.json, package.json, src/app/(component)/tasklist/page.tsx, src/app/components/common/dropdown/DropdownItem.tsx, src/app/components/common/input/Input.tsx, src/app/components/tasklist/CreateTaskModal.tsx, src/app/components/tasklist/CustomCalendar.tsx, src/app/components/tasklist/DateTimeSeletor.tsx, src/app/components/tasklist/RepeatSelector.tsx, src/app/components/tasklist/TaskCardDropdown.tsx, src/app/components/tasklist/TimeSelector.tsx, src/app/constants/dateConstants.ts, src/app/lib/task/postRecurringTask.ts, src/app/styles/globals.css, src/app/types/task.ts, src/app/utils/formValidation.ts, src/app/utils/formatTime.ts, tailwind.config.ts
close #31 
- 할 일 추가 모달 구현
- `/tasklist` 에서 할 일 추가 버튼 클릭 시 UI 확인 가능합니다.
- hover 디자인, 커스텀 스크롤 바, 월 반복 선택시 보이는 UI는 피그마에 없어서 프로젝트 디자인에 맞게 구현 했습니다.
- 유효성 검사는 따로 넣지 않았고 모든 요소가 입력이 되어야 버튼이 활성화 되도록 구현했고, 필수값임을 알 수 있도록 라벨 뒤에 '*'을 추가했습니다. (`주 반복`시 하나 이상의 요일, `월 반복`시 하나의 날짜까지 들어가야 버튼 활성화)
- 중간에 컴포넌트화 하여 코드를 줄인 부분이 많아서 changed files 탭에서 봐주시면 감사하겠습니다😄
=> #31 task list/task modal

src/app/components/myhistory/HistoryList.tsx
close #79 
formatDate 버셀오류 수정했습니다.
=> fix: formatDate 버셀오류 수정

package-lock.json, package.json, src/app/lib/group/getGroupById.ts
close #88 
- any 타입 명시화
- axios 버전 `0.14.4`로 업그레이드
=> Fix: 타입 명시화 및 axios 버전 업그레이드

src/app/components/team/HeaderDropdown.tsx, src/app/components/team/TaskListDropdown.tsx, src/app/components/team/TeamHeader.tsx, src/app/components/team/TodoList.tsx
close #45 
- 팀 미팅시간에 논의했던 타입 에러에 대한 수정작업을 진행했습니다.
베이스(develop) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.
ex) 결과물에 대한 스크린 샷
=> 팀 페이지 타입 에러 수정

src/app/components/team/TaskListDropdown.tsx
close #45 
- 빌드시 발생한 에러를 파악해 queryKey를 추가해 해결했습니다.
베이스(feature) 브랜치에 포함되기 위한 코드는 모두 정상적으로 작동이 되어야 합니다.
ex) 결과물에 대한 스크린 샷
=> 팀 페이지 queryKey추가

package-lock.json, src/app/(routes)/addboard/page.tsx, src/app/(routes)/boards/[boardid]/editboard/page.tsx, src/app/(routes)/mypage/page.tsx, src/app/components/boarddetail/CommentDropdown.tsx, src/app/components/boarddetail/CommentList.tsx, src/app/components/boarddetail/DeleteCommentModal.tsx, src/app/components/mypage/DeleteAccount.tsx, src/app/components/mypage/NicknameChanger.tsx, src/app/components/mypage/ProflieChanger.tsx, src/app/components/mypage/ResetPassword.tsx, src/app/components/mypage/ResetPasswordModal.tsx, src/app/lib/user/patchUser.ts
close #79 
- 마이페이지 이미지 업로드
- 닉네임 변경
- 게시글 수정 페이지 퍼블리싱
https://github.com/user-attachments/assets/09132711-3d46-40fb-bddb-88ac0dfee3d1
- 게시글 수정은 제가 일정이 있어서 내일 해야할 것 같습니다 ㅜㅜ
- 닉네임 변경시 헤더에 구현되지 않는 이슈가 있습니다!
=> mypage 이미지 업로드 및 닉네임 변경 구현

src/app/components/tasklist/CreateTaskModal.tsx
close #65 
https://github.com/user-attachments/assets/ac4ba232-76e5-4b31-8077-49c3a83dac79
=> 할 일 추가 모달에서 중복 요청 방지

src/app/(routes)/boards/[boardid]/editboard/page.tsx, src/app/components/boarddetail/BoardDetail.tsx, src/app/components/boarddetail/CommentList.tsx, src/app/components/editboard/ArticleChanger.tsx, src/app/components/editboard/ImageChanger.tsx, src/app/components/mypage/ProflieChanger.tsx, src/app/lib/article/patchArticle.ts, src/app/lib/image/postImage.ts
close #101 
- 수정하기 버그 수정
- 이미지 업로드 확인 모달 추가
https://github.com/user-attachments/assets/dfa4dc79-bc34-49ca-b767-afa420d5efae
https://github.com/user-attachments/assets/648d5eef-62a5-4d5f-b20a-8826cbaa7ab8
=> 수정하기 버그 수정 및 이미지 업로드 확인 모달 추가

src/app/(routes)/boards/page.tsx, src/app/components/boards/BoardsSearchBar.tsx, src/app/components/boards/BoardsSkeleton.tsx, src/app/components/boards/CommonAriticleCard.tsx, src/app/hooks/useArticleActions.ts, src/app/styles/globals.css, tailwind.config.ts
- #69 
- 게시글 더보기버튼 점 세개가 아니라 플러스 버튼으로 되어있음 -> 점 세개로 수정완료
- 검색 하면서 검색 내용이 동시에 검색되는 것 보다 엔터나 돋보기 버튼을 눌렀을 때 검색 결과 보이게 수정완료
- 글쓰기 버튼 위치 `xl`, `2xl` 태일윈드에서 제공하는 레이아웃 기준으로 변경
- 스켈레톤 추가완료
- pc레이아웃 변경완료(코드리뷰 반영)
https://github.com/user-attachments/assets/9e0811de-c8de-4b13-a1ee-6848eb1b5f0c
(네트워크설정 : 느린4G로 설정하여 확인했습니다.)
https://github.com/user-attachments/assets/2835428d-878a-4fb2-80a6-1b3f5f2b9a0e
- 테스트해보시고 이슈있으면 말해주시면 감사합니다~!
=> 자유 게시판 관련 부분 수정완료, 스켈레톤 추가완료

src/app/components/editboard/ArticleChanger.tsx
close #101 
- textarea custom scrollbar 추가
- 게시글 제목 200자 초과 방지 로직 추가
https://github.com/user-attachments/assets/804641bb-181b-4711-98e1-b3ea85e75ba0
- custom scrollbar는 가장 기본적인걸로 해놨는데, 별로인 것 같으면 빠르게 수정이 가능한 부분이니 편하게 말씀해주시면 다시 수정하겠습니다!
- 인풋, 호버 리팩토링은 자유게시판 상세페이지 이슈 해결 후 한번에 PR 올리겠습니다!
=> 자유게시판 수정페이지 이슈 해결

src/app/components/boards/CommonAriticleCard.tsx
- #69 
- 수정하기, 삭제하기 버튼 누르는 아이콘 지윤님이 만들어 놓은 `TaskCardDropdown` 으로 변경완료
https://github.com/user-attachments/assets/3d0719be-6f8a-4457-b508-9e0c1fcc43c0
=> 자유게시판 : 수정하기 삭제하기 보이는 버튼 아이콘 IconMore->TaskCardDropDown으로 변경완료

src/app/(routes)/[teamid]/edit/page.tsx, src/app/(routes)/addboard/page.tsx, src/app/(routes)/addteam/page.tsx, src/app/(routes)/boards/[boardid]/editboard/page.tsx, src/app/(routes)/invitation/page.tsx, src/app/components/auth/callback/KaKaoCallback.tsx, src/app/components/boarddetail/AddComment.tsx, src/app/components/boarddetail/BoardDetail.tsx, src/app/components/boarddetail/CommentList.tsx, src/app/components/boarddetail/DeleteArticleModal.tsx, src/app/components/editboard/ArticleChanger.tsx, src/app/components/mypage/DeleteAccount.tsx, src/app/components/mypage/NicknameChanger.tsx, src/app/components/mypage/ResetPasswordModal.tsx, src/app/components/resetpassword/ResetPasswordForm.tsx, src/app/components/taskdetail/TaskDetail.tsx, src/app/components/tasklist/TaskCard.tsx, src/app/components/team/MemberCard.tsx, src/app/components/team/TaskListDropdown.tsx, src/app/components/team/TodoList.tsx, src/app/hooks/useArticleActions.ts, src/app/hooks/useAuthRedirect.ts, src/app/hooks/useConfirmPassword.ts, src/app/hooks/useRedirectIfNotMember.ts, src/app/hooks/useResetPassword.ts, src/app/hooks/useSignIn.ts, src/app/hooks/useSignUp.ts
close #134
- 토스트 메시지 통일
https://github.com/user-attachments/assets/bd771303-6c73-476e-bbce-b9ce11cbe12f
- 누락된 부분 알려주시면 감사하겠습니다!
=> Toast message 통일

src/app/components/team/TaskListDropdown.tsx, src/app/components/team/TodoList.tsx
- 할 일 목록 드래그 시도시 화면이 움직임이 없도록 수정했습니다.
https://github.com/user-attachments/assets/8e8c3adb-5bb8-4bc3-8176-8be2d188cd79
=> TodolistItem 드래그 시도시 화면 움직임 없도록 수정

src/app/components/common/header/TeamHeaderDropdown.tsx
- teamheader 가운데 정렬 추가
- **적용 전**
- **적용 후**
=> teamheader 가운데 정렬 추가

src/app/components/common/header/TeamHeaderDropdown.tsx, src/app/components/common/modal/Modal.tsx
- teamheader 가운데 정렬 추가
- **적용 전**
- **적용 후**
=> 이슈(teamheader 가운데 정렬 추가) Feature->main으로 병합
